import product1 from "../assets/product1.png";
import product2 from "../assets/product2.png";
import product3 from "../assets/product3.png";
import product4 from "../assets/product4.png";
import product5 from "../assets/product5.png";
import product6 from "../assets/product6.png";
import product7 from "../assets/product7.png";
import product8 from "../assets/product8.png";
import product9 from "../assets/product9.png";
import product10 from "../assets/product10.png";

export const products = [
  {
    id: "1",
    image: product1,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 6000,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "2",
    image: product2,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 4800,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "3",
    image: product3,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 5290,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "4",
    image: product4,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 6000,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "5",
    image: product5,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 3400,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "6",
    image: product6,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 6000,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "7",
    image: product7,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 4800,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "8",
    image: product8,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 5290,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "9",
    image: product9,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 2800,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "10",
    image: product10,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 3400,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "11",
    image: product1,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 4500,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "12",
    image: product2,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 5300,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "13",
    image: product3,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 4300,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "14",
    image: product4,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 2500,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
  {
    id: "15",
    image: product5,
    name: "Краска Wallquest, Brownsone MS90102",
    price: 5000,
    isNew: false,
    isHave: false,
    isContract: false,
    isExclusive: false,
    isSale: false,
  },
];
